enviroments:
    #'1 Host X 1 V100': 1
    #'1 Host X 2 V100': 2
    #'1 Host X 4 V100': 4
    #'1 Host X 8 V100': 8
    '2 Host X 8 V100': 16
    # '4 Host X 8 V100': 32
    # '8 Host X 8 V100': 64
    # '32 Host X 8 V100': 256

device:
    'TeslaV100'

platform:
    'pytorch'

baseline_path:
    'ai_simulator/simulator_benchmark/data/torch/baseline.json'

resource_pool_path:
    'ai_simulator/simulator_benchmark/data/resource_pool.yaml'

nccl_path:
    './'

tasks:
    bert_large_b4:
        model:
            'bert_large'
        type:
            'NLP'
        batch_size:
            4
        graph_path:
           'ai_simulator/simulator_benchmark/data/torch/graphs/bert_large_b4.json'
        graph_path_multi_gpu:
           'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/bert_large_b4.json'
        database_path:
           'ai_simulator/simulator_benchmark/data/torch/database/bert_large_b4_db.json'
    GPT2_b4:
        model:
            'gpt2'
        type:
            'NLP'
        batch_size:
            4
        graph_path:
           'ai_simulator/simulator_benchmark/data/torch/graphs/GPT2_b4.json'
        graph_path_multi_gpu:
           'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/GPT2_b4.json'
        database_path:
           'ai_simulator/simulator_benchmark/data/torch/database/GPT2_b4_db.json'
    vgg19_b32:
        model:
            'vgg19'
        type:
            'CV'
        batch_size:
            32
        graph_path:
           'ai_simulator/simulator_benchmark/data/torch/graphs/vgg19_b32.json'
        graph_path_multi_gpu:
           'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/vgg19_b32.json'
        database_path:
           'ai_simulator/simulator_benchmark/data/torch/database/vgg19_b32_db.json'
    resnet152_b64:
        model:
            'resnet152'
        type:
            'CV'
        batch_size:
            64
        graph_path:
            'ai_simulator/simulator_benchmark/data/torch/graphs/resnet152_b64.json'
        graph_path_multi_gpu:
            'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/resnet152_b64.json'
        database_path:
            'ai_simulator/simulator_benchmark/data/torch/database/resnet152_b64_db.json'
