enviroments:
    '1 Host X 1 V100': 1
    '1 Host X 2 V100': 2
    # '1 Host X 4 V100': 4
    # '1 Host X 8 V100': 8
    # '2 Host X 8 V100': 16
    # '4 Host X 8 V100': 32
    # '8 Host X 8 V100': 64
    # '32 Host X 8 V100': 256

device:
    'TeslaV100'

platform:
    'pytorch'

baseline_path:
    'ai_simulator/simulator_benchmark/data/torch/baseline.json'

resource_pool_path:
    'ai_simulator/simulator_benchmark/data/resource_pool.yaml'

nccl_path:
    './'

tasks:

    vgg19:
        graph_path:
           'ai_simulator/simulator_benchmark/data/torch/graphs/vgg19.json'
        graph_path_multi_gpu:
           'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/vgg19.json'
        database_path:
           'ai_simulator/simulator_benchmark/data/torch/database/vgg19_db.json'
    resnet152:
        graph_path:
            'ai_simulator/simulator_benchmark/data/torch/graphs/resnet152.json'
        graph_path_multi_gpu:
            'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/resnet152.json'
        database_path:
            'ai_simulator/simulator_benchmark/data/torch/database/resnet152_db.json'

